version = 1

test_patterns = ["/src/__tests__/*.test.js"]

exclude_patterns = [
    "/bin/**",
    "/examples/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]
